### ISSUE TITLE
Broken links on README

### ISSUE THREAD

**Issue by vinomaster** [zos-spark/scala-workbench#6]
These links are broken on README :

Spark assembly: Download the spark-assembly-1.5.2-hadoop2.6.0.jar file and save it in the project home. This is part of IBM z/OS Platform for Apache Spark obtained through ShopzSeries.

Spark Kernel: Download the spark-kernel-0.1.5-SNAPSHOT_zOS.zip and save it in the project home. This can be obtained from IBM Developer Works.

**Comment by riceda195** [comment]
Both links have been updated.  Instructions for getting the product from ShopzSeries are still coming.
